apiVersion: v1
kind: Service
metadata:
  name: house-pred-frontend-service
  labels:
    app: house-pred-frontend
spec:
  selector:
    app: house-pred-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: NodePort  # Exposes the service externally